[package]
name = "challonge"
version = "0.1.0"
authors = ["Victor Polevoy <maintainer@vpolevoy.com>"]

description = "Client library for the Challonge API"
readme = "README.md"
license = "GPLv3"
keywords = ["challonge", "tourney", "tournament", "api", "system"]

repository = "https://github.com/vityafx/challonge-rs"
#documentation = "http://wombat.platymuus.com/rustdoc/discord_0.5.0/"

[dependencies]
hyper = "0.9.7"
serde_json = "*"
chrono = "0.2"
log = "0.3.6"
url = "1.1.1"
